// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0037:Usar o nome do membro inferido", Justification = "<Pendente>", Scope = "member", Target = "~M:MatrizTributaria.Controllers.NivelController.LerGravar~System.Web.Mvc.JsonResult")]
[assembly: SuppressMessage("Style", "IDE0029:Usar a expressão de união", Justification = "<Pendente>", Scope = "member", Target = "~M:MatrizTributaria.Controllers.TributacaoController.EditCstPisCofinsSaidaMassa(System.String,System.String,System.String,System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Style", "IDE0029:Usar a expressão de união", Justification = "<Pendente>", Scope = "member", Target = "~M:MatrizTributaria.Controllers.TributacaoController.EditCstVendaVarCFMassa(System.String,System.String,System.String,System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Style", "IDE0029:Usar a expressão de união", Justification = "<Pendente>", Scope = "member", Target = "~M:MatrizTributaria.Controllers.TributacaoController.EditCstVendaVarContMassa(System.String,System.String,System.String,System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.SetorProdutos.id")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.SetorProdutos.descricao")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.SetorProdutos.tributacoes")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.id")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.estado")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.idProduto")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.idSetor")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.fecp")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.codNatReceita")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstEntradaPisCofins")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstSaidaPisCofins")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqEntPis")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqSaidaPis")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqEntCofins")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqSaidaCofins")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.idFundamentoLegal")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstVendaAtaCont")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsVendaAtaCont")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsSTVendaAtaCont")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsVendaAtaCont")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsSTVendaAtaCont")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstVendaAtaSimpNacional")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsVendaAtaSimpNacional")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsSTVendaAtaSimpNacional")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsVendaAtaSimpNacional")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsSTVendaAtaSimpNacional")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstVendaVarejoCont")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsVendaVarejoCont")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsSTVendaVarejo_Cont")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcVendaVarejoCont")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstVendaVarejoConsFinal")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsVendaVarejoConsFinal")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsSTVendaVarejoConsFinal")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsVendaVarejoConsFinal")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsSTVendaVarejoConsFinal")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.idFundLegalSaidaICMS")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.idFundLelgalEntradaICMS")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstCompraDeInd")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsCompDeInd")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsSTCompDeInd")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsCompraDeInd")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsSTCompraDeInd")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstCompradeAta")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsCompradeAta")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsSTCompraDeAta")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsCompraDeAta")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsSTCompraDeAta")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstCompradeSimpNacional")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsCompradeSimpNacional")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsSTCompradeSimpNacional")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsCompradeSimpNacional")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.redBaseCalcIcmsSTCompradeSimpNacional")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstdaNfedaIndFORN")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstdaNfedeAtaFORn")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsNFE")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsNfeSN")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.aliqIcmsNfeAta")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.tipoMVA")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.valorMVAInd")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.inicioVigenciaMVA")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.fimVigenciaMVA")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.creditoOutorgado")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.valorMVAAtacado")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.regime2560")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.dataCad")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.dataAlt")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstPisCofinsE")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.cstPisCofinsS")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.fundamentoLegal")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.naturezaReceita")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.produtos")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~P:MatrizTributaria.Models.Tributacao.setorProdutos")]
[assembly: SuppressMessage("Style", "IDE0029:Usar a expressão de união", Justification = "<Pendente>", Scope = "member", Target = "~M:MatrizTributaria.Controllers.TributacaoController.EditCstVendaAtaContMassa(System.String,System.String,System.String,System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Style", "IDE0029:Usar a expressão de união", Justification = "<Pendente>", Scope = "member", Target = "~M:MatrizTributaria.Controllers.TributacaoController.EditCstVendaAtaSNMassa(System.String,System.String,System.String,System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Style", "IDE0029:Usar a expressão de união", Justification = "<Pendente>", Scope = "member", Target = "~M:MatrizTributaria.Controllers.TributacaoController.EditCstEntradaPisCofinsMassa(System.String,System.String,System.String,System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Style", "IDE0029:Usar a expressão de união", Justification = "<Pendente>", Scope = "member", Target = "~M:MatrizTributaria.Controllers.TributacaoController.EditCstPisCofinsEntradaMassa(System.String,System.String,System.String,System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})~System.Web.Mvc.ActionResult")]
